name = "ruqola"
version = "0.1.0"
defaultTargets = ["ruqola"]

[[lean_lib]]
name = "Ruqola"

[[lean_exe]]
name = "ruqola"
root = "Main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "d1d1e4b72c6e009edd97cabe1d661b021fe8eeae"

[[require]]
name = "REPL"
git = "https://github.com/leanprover-community/repl.git"
rev = "7df77c0a1c9188ab58c76d4138a06ae5e0c32282"
